import React from 'react';
import { BrowserRouter as Router, Routes, Route } from 'react-router-dom';
import { Amplify } from 'aws-amplify';
import { withAuthenticator } from '@aws-amplify/ui-react';
import '@aws-amplify/ui-react/styles.css';

// Components
import Header from './components/Header';
import Dashboard from './pages/Dashboard';
import FormCreate from './pages/FormCreate';
import FormView from './pages/FormView';
import NotFound from './pages/NotFound';

// Amplify configuration
// This would typically come from an aws-exports.js file generated by Amplify CLI
// For now, we'll use a placeholder
const amplifyConfig = {
  Auth: {
    region: process.env.REACT_APP_AWS_REGION || 'us-east-1',
    userPoolId: process.env.REACT_APP_USER_POOL_ID,
    userPoolWebClientId: process.env.REACT_APP_USER_POOL_CLIENT_ID
  },
  API: {
    endpoints: [
      {
        name: 'formBuilderApi',
        endpoint: process.env.REACT_APP_API_ENDPOINT,
        region: process.env.REACT_APP_AWS_REGION || 'us-east-1'
      }
    ]
  }
};

// Initialize Amplify
Amplify.configure(amplifyConfig);

function App({ signOut, user }) {
  return (
    <Router>
      <div className="app">
        <Header user={user} signOut={signOut} />
        <main className="main-content">
          <Routes>
            <Route path="/" element={<Dashboard />} />
            <Route path="/create" element={<FormCreate />} />
            <Route path="/forms/:formId" element={<FormView />} />
            <Route path="*" element={<NotFound />} />
          </Routes>
        </main>
      </div>
    </Router>
  );
}

// Wrap the App component with the Amplify withAuthenticator HOC
export default withAuthenticator(App);
